### ISSUE TITLE
Manufactured Item Quantity and Package Item Quantity

### ISSUE THREAD

**Issue by costateixeira** [hl7-eu/unicom-ig#11]

**Comment by rlindstrm** [comment]
Let’s take a product. It’s a box containing 2 syringes, 0.6ml each. It looks like this:

![image](https://user-images.githubusercontent.com/112903984/194477913-96f58880-f501-4d0d-b141-ad699dffadad.png)

 It would be described as:
 
![image](https://user-images.githubusercontent.com/112903984/194477959-c9a542d3-0ea8-4e98-b092-53e898dac00f.png)


You can see full xml [here](https://idmp-viewer.azurewebsites.net/display-product?url=http://ppl02.azurewebsites.net/MedicinalProductDefinition/Clexane-60mg-0.6ml-sol-inj-EE-MPD) (open it in debug mode in upper right corner).
Fsh file [here](https://github.com/medigree/ee-idmp/blob/master/input/fsh/products/Clexane-60mg-0.6ml-EE.fsh).

In ISO standard:

![image](https://user-images.githubusercontent.com/112903984/194478001-e01913cb-88fe-4027-aba2-48220a442f04.png)

In FHIR PackagedProductDefinition, we have containedItem, which is described as the number of items within this packaging (referring to units of presentation, rather than millilitres). 

![image](https://user-images.githubusercontent.com/112903984/194478032-2e192657-bdee-442f-8c4f-3961d729ce1c.png)

However, there is no place for the size of syringe in the ManufacturedItemDefinition, where it logically belongs. 
It is also not clear in the spec how to define the size of a syringe/vial/tube etc in PackagedProductDefinition.

**Proposal**: either 
1) have the size of the manufactured item in ManufacturedItemDefinition; or 
2) Change the description of containedItem.amount so that it would include the size of the manufactured item.

**Comment by gcangioli** [comment]
https://jira.hl7.org/browse/FHIR-39130
