### ISSUE TITLE
Update product viewer templates

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#110]
José updates the liquid updates in his repository and will let us know when it's done. https://github.com/costateixeira/prodviewer/

Then DW updates their templates.

**Comment by rlindstrm** [comment]
Done, says José.
DW can try now. :)

**Comment by costateixeira** [comment]
the product viewer is now updated. 
Because there are some minor adaptations to do because of liquid syntax, I made a commit that shows what needs to change when updating the templates from the IG to the viewer:
* replace "bundle.entry" with "entry"
* in the includes, replace `include xxx.liquid yyy=yyy` (which is just passing a variable with an alias equal to the variable name) with `include './yyy.liquid' with yyy` - i.e.
  * add a single quote on the file name
  * only use the variable name and the keyword "with"
  * don't forget the relative path ./

Here's an example:
https://github.com/costateixeira/prodviewer/commit/6eb3788e2a840088a482c1ec82aa054220f70274

**Comment by costateixeira** [comment]
this is ready to test. The changes to the template are there just to show how I adapted these templates from the IG template. The prodViewer is ready to be deployed and tested

**Comment by simodiaco** [comment]
We have updated the prodViewer on the server [jpa.unicom.datawizard.it/apps/productlist/index.html](https://jpa.unicom.datawizard.it/apps/productlist/index.html)
[Here](https://jpa.unicom.datawizard.it/apps/visualiser/index.html?url=https://jpa.unicom.datawizard.it/fhir/MedicinalProductDefinition/AMLkrka-5mg-Tablet-SE-IS-MedicinalProductDefinition) an example

We have to use the @costateixeira docker image because the official 'hapiproject' image cannot handle it.

**Comment by rlindstrm** [comment]
Action item for José, but not in this project. Closed for now.
