### ISSUE TITLE
Figure out what Validation is doing

### ISSUE THREAD

**Issue by costateixeira** [hl7-eu/unicom-ig#119]
example: 
https://jpa.unicom.datawizard.it/fhir/MedicinalProductDefinition/ABESYL-CAPS-10MG-CAP-204-GRC-MPD/$validate

**Comment by rlindstrm** [comment]
Slice order error is probably legit, because I do have ordered slices in the spec for name parts. We can unorder them.
The terminology error is weird. The code system exists and the code also exists, everything seems correct. 

Also, I think the validation button only validates MedicinalProductDefinition, which is not that helpful.

**Comment by rlindstrm** [comment]
Rutt makes slices unordered.

**Comment by rlindstrm** [comment]
Rutt made slices unordered.
Bundle validation discussed under #120 
Terminology error unexplained.
