### ISSUE TITLE
4-substance csv import findings

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#124]
I have created a GoogleDoc with findings about as-is data imports, and I asked Robert to go through the list and see what can be improved.

[The file is here.](https://docs.google.com/document/d/1fDnPPIgTPSxUfCNNrsRRgNSCx8fFk_wUKuSfRgQKOtk/edit?usp=sharing)

Product browser with the data is [here](https://jpa.unicom.datawizard.it/apps/productlist/index.html).

**Comment by G-DPP** [comment]
Regarding the point "Manufactured item is not linked to package" the problem is a combination of missing data and the query made by the visualiser (#125). The mnufactured item was only missing in the Greek and Belgian data. The Manufactured item is visible in the visualiser with the temporary solution given in #125.
