### ISSUE TITLE
Specify FHIR resources for using in clinical documents

### ISSUE THREAD

**Issue by costateixeira** [hl7-eu/unicom-ig#44]
Several options, we don't have strict guidance yet on which one is best.

1. Prescription contains Medication as normal, and that Medication has extensions for the attributes
1.1. Prescription contains additional Medication besides the original, and that new Medication has extensions for the attributes
2. Prescription contains Medication which has the link to a contained MedicationKnowledge, and that MedicationKnowledge has the attributes
2.1. Prescription contains additional MedicationKnowledge (same as above but Medication stays as is, the extension is on Prescription)
3. We use the medication definitional resources
4. ...

**Comment by rlindstrm** [comment]
The version here is also 4.3.0? 
Because for MedicationKnowledge, the difference between R4B and R5 is very big.

My gut feeling says Medication is more IDMP-compatible than MedicationKnowledge. But actual analysis would be welcome (and please include combination packages like Canifug Cremolum and Qlaira). 

MedicationDefinition module resources would probably not look good on a prescription, but again, it would be correct to have a reasoning to go with the decision.

**Comment by rlindstrm** [comment]
Beyond UNICOM scope.
