### ISSUE TITLE
Have a visualizer for product data & mark that data is for testing purposes

### ISSUE THREAD

**Issue by costateixeira** [hl7-eu/unicom-ig#60]
Can reuse Rik Smithies's visualizer, or create a new one.

The visualizer should clearly display that the data is "Work in progress".

**Comment by rlindstrm** [comment]
I checked the EMA IG and looks like MedicinalProductDefinition.status is not occupied by any other meaningful content, and could be used to express that the data is for testing purposes. 
Of all the resources, RegulatedAuthorization seems to be the only one where .status has a specific meaning. Please don't overwrite it there.

@costateixeira and @joofio please talk to eachother and decide who does what in this issue and assign accordingly.

**Comment by Censacrof** [comment]
@rlindstrm, correct me if I'm wrong: I think that the "mark that data is for testing purposes" part should be accomplished at the FHIR level. I think that all resources have a "status" attribute where you can have as a value "active", "draft", etc...

**Comment by rlindstrm** [comment]
Not sure what you mean by FHIR level. Like a level higher than status of the resource? Or you mean the status?
I don't really care anyway. We just agreed to have it SOMEWHERE, all suggestions are welcome.  :)

But it's important to know that RegulatedAuthorization.status is used for the status of marketing authorisation. It is not metadata for the resource, but semantically relevant bit of data. So this one must not be changed.

**Comment by Censacrof** [comment]
I actually meant the "status". I'm simply saying that the information about the maturity of data should be in the data itself, and not just a banner in the visualizer front-end saying "this data is just for playing around".

**Comment by rlindstrm** [comment]
Yes, absolutely agreed.

**Comment by rlindstrm** [comment]
Visualiser uses this request to bundle the resources:
http://fhir.hl7.pt/fhir/MedicinalProductDefinition?_revinclude=RegulatedAuthorization:subject&_revinclude=PackagedProductDefinition:package-for&_revinclude=AdministrableProductDefinition:form-of&_include:iterate=AdministrableProductDefinition:manufactured-item&_revinclude:iterate=Ingredient:for&_format=json&_id=mp-6747a4bfd435b641b93387c863011a5d

If I understand correctly __include:iterate=AdministrableProductDefinition:manufactured-item_ collects all the Manufactured Items referenced in the Administrable Product resource. This is not a good place for retrieving this data, as this reference is not present in IDMP and is generally not present in the NCA data either (we had the reference in UFIS data, that's why it worked well with those examples). 
The best place to search for Manufactured Items is the package.

**Comment by rlindstrm** [comment]
Marketing authorisation holder name comes from Organization resource which is not present in the bundle. Please include if possible.

**Comment by rlindstrm** [comment]
I'd also like to change some labels on the template, starting from 
_Combined pharmaceutical dose form: {{ mpd.combinedPharmaceuticalDoseForm.coding[0].display }}_
where I'd like to use the term "Authorised dose form" instead (see [Known Issues ](https://build.fhir.org/ig/hl7-eu/unicom-ig/branches/mpd-r4b/issues.html#authorised-dose-form)for explanation). 

But there other tiny things I'd like to correct in labels, so I'm not sure if you want the list or if I should just write them in the template. @costateixeira

**Comment by costateixeira** [comment]
> Visualiser uses this request to bundle the resources: http://fhir.hl7.pt/fhir/MedicinalProductDefinition?_revinclude=RegulatedAuthorization:subject&_revinclude=PackagedProductDefinition:package-for&_revinclude=AdministrableProductDefinition:form-of&_include:iterate=AdministrableProductDefinition:manufactured-item&_revinclude:iterate=Ingredient:for&_format=json&_id=mp-6747a4bfd435b641b93387c863011a5d
> 
> If I understand correctly __include:iterate=AdministrableProductDefinition:manufactured-item_ collects all the Manufactured Items referenced in the Administrable Product resource. This is not a good place for retrieving this data, as this reference is not present in IDMP and is generally not present in the NCA data either (we had the reference in UFIS data, that's why it worked well with those examples). The best place to search for Manufactured Items is the package.

@rlindstrm the references are fixed (they were already somewhat handled in the template layout, but the query was indeed incorrect. 
As for the Orgs, is there an example of a product that has an org for which there is an Organization resource?
For the other tiny things - i'll publish the template and we can use that for adding issues. Or a email, or a document, or a comment here...

**Comment by rlindstrm** [comment]
All the bundle examples in the IG use Organization resource.
Joao's data also uses Organization, because it's written in the profile.

The main reason for this solution is that I didn't know how else to profile it. There is an open question about it in the profile fsh file, which we can revisit if having a separate Organization resource seems too much (we only need the identifier and the name).

**Comment by costateixeira** [comment]
The point is whether the resoluções are on the server. For example
Cefuroxim does reference an organization but there are no Organization
resources in Hugh 's server.

**Comment by rlindstrm** [comment]
I'm not sure if it was a question or an answer. 
In UFIS we did not have Organization resources. In IG we always have, and they are also present in the bundle-examples, even if it's not maybe necessary.

**Comment by costateixeira** [comment]
ok. What do we want to see about the organization?

**Comment by rlindstrm** [comment]
Name and identifier(s)

**Comment by rlindstrm** [comment]
Dear @costateixeira 
You wrote in the email that it's fixed, but I have no idea how I could use it.
I've been using it here http://185.11.167.107:8084/  
Is that under your control? Can you update it please? Should I use it some place else?

**Comment by rlindstrm** [comment]
I know you haven't updated the visualiser yet, but here's another anomaly. This is from browser's Network tab:
![image](https://user-images.githubusercontent.com/112903984/210171004-33fe10c3-107b-45d8-909f-967defc8c69a.png)

So... Basically, when I search for one product, I actually get another one in the visualiser. You can try it out on this link, but it seems to apply to all products at the moment:
http://185.11.167.107:8084/apps/visualiser/index.html?url=http://fhir.hl7.pt/fhir/MedicinalProductDefinition/mp-45f0935e8c6afee1cac2e42562b88f23

**Comment by costateixeira** [comment]
I was debugging the visualizer (the recursive packaging has been a pain).
Will continue to update and fix as soon as I can

**Comment by rlindstrm** [comment]
The first version of near-functional visualiser is here: https://hl7-eu.github.io/unicom-ig/branches/template-work/Bundle-001-Agen5mg-EE-FullProduct.html
There's some template work to be done to beautify things up.

Out of 36 products that we have in the IG, there are 5 that don't open in the visualiser. I believe it does not like points in the Bundle id (or possibly in any other id). 
@costateixeira If that is an expected behaviour, then it's not difficult to get rid of points in all the id's. If that is something you want to investigate, then here are the ones that don't open (example number and MPD id):

003   CefuroximStragen-1.5g-Powder-SE-IS-MedicinalProductDefinition
006   Yaz-0023mg-tablet-SE-AJ-MedicinalProductDefinition
007   Jangee-0.02mg-3mg-Film-coated-tablet-EE-MPD
008   Jangee-0.03mg-3mg-Film-coated-tablet-EE-MPD
010   Clexane-60mg-0.6ml-solinj-EE-MPD

**Comment by costateixeira** [comment]
Dots in the bundle name do mess up the entire thing. Eventually there
should be a way to make it work but I have no ideas

**Comment by rlindstrm** [comment]
I worked on template-work branch:
- removed decimal points from ids
- did some prettying on templates, added some elements that were missing
- made a separate file for Ingredient
- the build fails on build.fhir.org, but I understood that this is expected at this point. It built in my computer.

@costateixeira 
I struggled with Ingredient a lot. Two things were missing /not working on your template, and I could not get them work either:
- reference strength (I added the block, but it only recognises if the reference strength is present in the data, but doesn't show real data). Please help me find what I'm missing.
- administrable product ingredients. I tried several ways, but they just don't want to appear. :)

**Comment by rlindstrm** [comment]
Done, I guess. Shall we close or wait until fhir.build also accepts our choices?
Also, a page in the IG is being written about the visualiser. Or it was being written yesterday. Who knows how it will continue. I would untie the page writing task from this issue.

**Comment by costateixeira** [comment]
Agree to close if it is acceptable for now, and the page is a separate task
