### ISSUE TITLE
Moiety - SubstanceDefinition vs ValueSet

### ISSUE THREAD

**Issue by Censacrof** [hl7-eu/unicom-ig#76]
In order to do a smart substitution, information about moieties of the substances is needed. We need to decide how to convey that information, as far as I know we have 2 options:

1. Use the *moiety* field of SubstanceDefinition
2. @costateixeira suggested to put that information directly in the *Substance* ValueSet (not clear how to me)

What are the implications of each approach? Which one is better?

**Comment by rlindstrm** [comment]
A relationship between two concepts should typically be defined in the code system not value set. That means we would create our own code system, because EMA SMS, which we claim to use, does not have that information.

In FHIR CodeSystem resource you can define the properties to create relationships between concepts. 
This one is an example I quickly made using SNOMED codes ([SNOMED has these relationships](https://browser.ihtsdotools.org/?perspective=full&conceptId1=384976003&edition=MAIN/2022-11-30&release=&languages=en) and I would argue that theoretically there is the third option of just using mapping to SNOMED and retrieving substance-moiety information from there).

{
  "resourceType": "CodeSystem",
  "title": "Substance-test",
  "url": "https://spor.ema.europa.eu/smstest",
  "status": "draft",
  "compositional": false,
  "content": "complete",
  "concept": [
    {
      "code": "386864001",
      "display": "Amlodipine"
    },
    {
      "code": "421048000",
      "display": "Amlodipine maleate",
      "property": [
        {
          "code": "Is modification of",
          "valueCode": "386864001"
        }
      ]
    },
    {
      "code": "384976003",
      "display": "Amlodipine besilate",
      "property": [
        {
          "code": "Is modification of",
          "valueCode": "386864001"
        }
      ]
    }
  ],
 
  "property": [
    {
      "code": "Is modification of",
      "type": "code"
    }
  ],
  "count": 3,
  "name": "Substance_test"
}

**Comment by rlindstrm** [comment]
Using SubstanceDefinition would allow us to work with molecular masses and fill in the missing data about (reference) strengths. However, I personally don't feel confident enough to go there. 
Also, using SubstanceDefinition would help us indicate that life would be easier if this data came from SMS code system, and we wouldn't have to create resources just to connect salts with moieties. 
If we improve the substance code system manually, we have to be clear in our communication that this is not something publicly available in SMS.

**Comment by RobertVanderStichele** [comment]
Dear Rutt and José, 

For the Unicom Pilot Product list we have the codes for moeity and moiety+modifier, substance with the role of PAI and the relationships. 
[SubtancesCodeTemplate_RVS_V5.xlsx](https://github.com/hl7-eu/unicom-ig/files/10256875/SubtancesCodeTemplate_RVS_V5.xlsx)


Annet Rozema is preparing a deliverable with the gap analysis between needs of UNICOM and current public output. 

Molecular mass and hierarchy of substances is part of it.

**Comment by RobertVanderStichele** [comment]
Resources to support the legacy conversion such as the one above, should be also in the sharepoint for broader availability. 
Comments or suggestions for improvement can be in github.

**Comment by costateixeira** [comment]
@rlindstrm will identify the way to do this in SNOMED CT using an existing server that we can use for demonstration purposes.
We don't want to redo this in FHIR CodeSystems for now.

**Comment by RobertVanderStichele** [comment]
Dear Rutt and José, 
Why do we need snomed codes for this. 
We have SMS codes and SPor codes for moiety and for moiety+modifier in SMS code. That what is needed in IDMP. 
It is the task of the NCA to say for each product whether a modifier is possible and if so which moiety+modifier is the right one for each product.  Amlodipine and ibuprofen have modifiers, carbamazepine and simvastatine do not. 
About one third of the substances do not need to identify a modifier, one third has only one modifier possible (and then no choice must be made), one third has 2 or more possible modifiers and then for each product a choice must be made. 

We have sufficient information with in SMS and UNICOM to describe all the variations of substance. We do not need SNOMED CT for that (although we have a conversion table for the 35 substances of the PPL, not only to snomed but also to CAS, UNII, and WHODRUG. 

EU-SRS is preparing a publicly available open source periodic output of the cleansed (non-confidential) substance data where molecular mass of moiety and moiety+modifier will be available, together with the code. 

 Robert

**Comment by rlindstrm** [comment]
Close this one, but relevant for aligning with ePI
