### ISSUE TITLE
Create minimal ValueSets to reduce qa errors

### ISSUE THREAD

**Issue by joofio** [hl7-eu/unicom-ig#84]
Creating Dummy Minimal ValueSets for the profiles to use in order to reduce QA errors for the time being and reduce deploy time.

**Comment by rlindstrm** [comment]
I tried 0..0 cardinality for elements that we don't use anyway, but the qa is still screaming about unresolved value set urls. It's just so stupid. 
Good news is that example bindings are good enough for overwriting the broken FHIR vs binding. 
Will continue, but be aware that I will be bitter.

**Comment by rlindstrm** [comment]
Now.. In r4b, there is just one of those value set qa errors left and it's in the PPLMedicinalProductDefinition profile about classification. I added the binding, but because of our overly sophisticated (possibly broken) slicing, it does not take the qa error away. 
I removed the slicing from the TransitionMedicinalProductDefinition profile and there the new binding did its job and the qa error disappeared (and Snapshot view appeared!). 

There are a few more errors, that I could not resolve. Maybe someone else could take over. I know some similar errors have been resolved before.

**Comment by rlindstrm** [comment]
I successfully fixed the url mismatch error.
But the product classification ones from PPLMedicinalProductDefinition profile are still there. The value set binding is there, but does not work unless I remove the slicing. Please Someone Smart check the slicing correctness, because it affects the snapshot view as well.

**Comment by rlindstrm** [comment]
Classification/ATC slicing removed, but the relief was brief, because all the prior errors are back, even though the profile defines local value sets. Not even making value set bindings required helps. 
![image](https://user-images.githubusercontent.com/112903984/212566470-0d0e6d31-4fa1-472f-91a8-201d44cc0227.png)

**Comment by rlindstrm** [comment]
[Related topic in FHIR chat](https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/QA.20issues.20from.20lower.20layers.20in.20the.20stack).

**Comment by rlindstrm** [comment]
Fixed in R5.
R4B cannot be helped, three errors remain.
